### ISSUE TITLE
Failing cython extension import

### ISSUE THREAD

**Issue by djhoese** [conda-forge/pyresample-feedstock#54] opened 2019-12-28 01:50 UTC
Issue:

Importing some/all of the cython extensions fails using the most recent build/version of pyresample.

Environment:

```
conda create -n test_pyresample python=3.7 pyresample
```

Failure can be seen with:

```
python -c "from pyresample.ewa import _ll2cr"
```

I tried doing `strace <above command>` and `python -vv` and didn't see anything useful. The `.so` file is there.

If I pip install the current master branch of pyresample then it works fine. I see a major difference in `.so` size between conda-forge and my pip installed version. From conda-forge:

```
$ ll ~/miniconda3/envs/test_pyresample/lib/python3.7/site-packages/pyresample/ewa/
total 704
drwxrwxr-x 3 davidh davidh   4096 Dec 27 19:31 ./
drwxrwxr-x 9 davidh davidh   4096 Dec 27 19:06 ../
-rwxrwxr-x 2 davidh davidh 379856 Dec 26 07:22 _fornav.cpython-37-x86_64-linux-gnu.so*
-rw-rw-r-- 2 davidh davidh  10874 Dec 27 19:31 __init__.py
-rwxrwxr-x 2 davidh davidh 311504 Dec 26 07:22 _ll2cr.cpython-37-x86_64-linux-gnu.so*
drwxrwxr-x 2 davidh davidh   4096 Dec 27 19:31 __pycache__/
```

From pip:

```
$ ll ~/miniconda3/envs/test_pyresample/lib/python3.7/site-packages/pyresample/ewa/
total 3788
drwxrwxr-x 3 davidh davidh    4096 Dec 27 19:39 ./
drwxrwxr-x 9 davidh davidh    4096 Dec 27 19:39 ../
-rwxrwxr-x 1 davidh davidh 2135480 Dec 27 19:39 _fornav.cpython-37m-x86_64-linux-gnu.so*
-rw-rw-r-- 1 davidh davidh   10873 Dec 27 19:39 __init__.py
-rwxrwxr-x 1 davidh davidh 1713688 Dec 27 19:39 _ll2cr.cpython-37m-x86_64-linux-gnu.so*
drwxrwxr-x 2 davidh davidh    4096 Dec 27 19:39 __pycache__/
```

@ocefpaf One thing I noticed is that the pyresample recipe doesn't use the same build command that other recipes I maintain use:

https://github.com/conda-forge/pyresample-feedstock/blob/92f6056e56b13cd35866c91a1e02a653fd877c4a/recipe/meta.yaml#L14

For example vispy:

https://github.com/conda-forge/vispy-feedstock/blob/464d4418c6f85c8d0d0b5385b267ef8c0e76a445/recipe/meta.yaml#L16

**Comment by djhoese** [comment] 2019-12-28 01:53
Forgot the output I'm seeing when running that python import:

```
$ python -c "from pyresample.ewa import _ll2cr"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/davidh/miniconda3/envs/test_pyresample/lib/python3.7/site-packages/pyresample/ewa/__init__.py", line 72, in <module>
    from pyresample.ewa import _ll2cr, _fornav
ImportError: cannot import name '_ll2cr' from 'pyresample.ewa' (/home/davidh/miniconda3/envs/test_pyresample/lib/python3.7/site-packages/pyresample/ewa/__init__.py)
```

Note we are seeing this on Travis CI for other projects that install pyresample.

**Comment by ocefpaf** [comment] 2020-01-07 21:25
> @ocefpaf One thing I noticed is that the pyresample recipe doesn't use the same build command that other recipes I maintain use.

That one should be fine though. The updated one just remove extra options to remove verbosity and options that are default in conda-build.

(Sorry for the delay to get here but it seems that the issue is fixe, right?)

**Comment by mraspaud** [comment] 2020-01-08 07:23
@ocefpaf thanks for the message, yes, it's fixed now :)

**Closed** 2020-01-10 18:25 UTC
Labels: bug
